; ---------------------------------------------------------------------------

builtin_sample_entry struc ; (sizeof=0x8)
offset:		dw ?			; offset
length:		dw ?
field_4:	dw ?
field_6:	dw ?
builtin_sample_entry ends

; ---------------------------------------------------------------------------

sample_entry	struc ;	(sizeof=0xA)
playing:	db ?
id:		db ?
bank:		db ?
offset:		dw ?			; offset
length:		dw ?
length_high_byte:db ?
length_low_word:dw ?
sample_entry	ends


; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2011 Hex-Rays, <support@hex-rays.com>	    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	4C74C06050DDF822A042753F1E447B32
; Input	CRC32 :	CDFE96B9

; File Name   :	Z:\home\marzojr\Documents\Source\sonicretro\smps\smps-ristar.bin
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 165Bh Loaded length: 165Bh

; Processor	  : z80	[]
; Target assembler: Zilog Macro	Assembler

; ===========================================================================

; Segment type:	Regular
		segment	ROM

; =============== S U B	R O U T	I N E =======================================

; Attributes: noreturn

EntryPoint:
		di
		di
		di
		ld	sp, sample1
		ld	hl, sample1
		ld	de, sample1.id
		ld	bc, 15h
		ld	(hl), 0
		ldir
		ld	a, 2Ah
		ex	af, af'


PCMwaitloop:				; CODE XREF: EntryPoint+1Aj
					; EntryPoint+1F1j
		ld	a, (driver_input)
		or	a
		jr	z, PCMwaitloop

		ld	(fm_in_progress_flag), a


busywait:				; CODE XREF: EntryPoint+23j
		ld	a, (zYM2612_A0)
		or	a
		jp	m, busywait

		ld	a, 2Bh
		ld	(zYM2612_A0), a
		ld	a, 80h
		ld	(zYM2612_D0), a
		xor	a
		ld	(fm_in_progress_flag), a


PCMplayloop:				; CODE XREF: EntryPoint+B9j
					; EntryPoint+149j ...
		xor	a
		ld	(driver_input),	a
		ld	ix, sample0
		call	LoadSampleData

		call	zMakeBankSwitch0

		exx
		ld	ix, sample1
		call	LoadSampleData

		call	zMakeBankSwitch1

		ld	hl, zBankRegister
		call	zBankSwitch0

		exx
		ld	h,  zYM2612_A0 >> 8
		ld	a, (sample0.playing)
		or	a
		jp	z, nosample0loop

		ld	a, (sample1.playing)
		or	a
		jp	z, sample0only


PCMplayloop_2samples:			; CODE XREF: EntryPoint+B6j
					; EntryPoint+CEj ...
		ld	a, e
		or	d
		jr	z, sample0bankdone

		ld	a, (bc)
		ld	l, a
		dec	de
		inc	bc
		exx

loc_6D:					; DATA XREF: zMakeBankSwitch1+6w
		ld	(hl), 0

loc_6F:					; DATA XREF: zMakeBankSwitch1+Dw
		ld	(hl), 0

loc_71:					; DATA XREF: zMakeBankSwitch1+14w
		ld	(hl), 0

loc_73:					; DATA XREF: zMakeBankSwitch1+1Bw
		ld	(hl), 0

loc_75:					; DATA XREF: zMakeBankSwitch1+22w
		ld	(hl), 0

loc_77:					; DATA XREF: zMakeBankSwitch1+29w
		ld	(hl), 0

loc_79:					; DATA XREF: zMakeBankSwitch1+30w
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	a, e
		or	d
		jr	z, sample1bankdone

		ld	a, (bc)
		dec	de
		inc	bc

loc_86:					; DATA XREF: zMakeBankSwitch0+6w
		ld	(hl), 0

loc_88:					; DATA XREF: zMakeBankSwitch0+Dw
		ld	(hl), 0

loc_8A:					; DATA XREF: zMakeBankSwitch0+14w
		ld	(hl), 0

loc_8C:					; DATA XREF: zMakeBankSwitch0+1Bw
		ld	(hl), 0

loc_8E:					; DATA XREF: zMakeBankSwitch0+22w
		ld	(hl), 0

loc_90:					; DATA XREF: zMakeBankSwitch0+29w
		ld	(hl), 0

loc_92:					; DATA XREF: zMakeBankSwitch0+30w
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		exx
		add	a, l
		rra
		ex	af, af'
		ld	l,  zYM2612_A0 & 0FFh
		ld	(fm_in_progress_flag), a


busywait_1:				; CODE XREF: EntryPoint+A3j
		bit	7, (hl)
		jr	nz, busywait_1

		ld	(hl), a
		ex	af, af'
		inc	hl
		ld	(hl), a
		xor	a
		ld	(fm_in_progress_flag), a
		ld	a, 3


pitchloop:				; CODE XREF: EntryPoint+B0j
		dec	a
		jr	nz, pitchloop

		ld	a, (driver_input)
		or	a
		jp	p, PCMplayloop_2samples

		jp	PCMplayloop

; ---------------------------------------------------------------------------

sample0bankdone:			; CODE XREF: EntryPoint+66j
		ld	ix, sample0
		ld	a, (ix+sample_entry.length_low_word)
		or	(ix+ sample_entry.length_low_word+1 )
		jr	z, sample0done

		call	DoNextSampleBank

		call	zMakeBankSwitch0

		jp	PCMplayloop_2samples

; ---------------------------------------------------------------------------

sample0done:				; CODE XREF: EntryPoint+C6j
		ld	(ix+sample_entry.playing), a
		jp	nosample0loop

; ---------------------------------------------------------------------------

sample1bankdone:			; CODE XREF: EntryPoint+81j
		ld	ix, sample1
		ld	a, (ix+sample_entry.length_low_word)
		or	(ix+ sample_entry.length_low_word+1 )
		jr	z, sample1done

		call	DoNextSampleBank

		call	zMakeBankSwitch1

		exx
		jp	PCMplayloop_2samples

; ---------------------------------------------------------------------------

sample1done:				; CODE XREF: EntryPoint+E1j
		ld	(ix+sample_entry.playing), a
		exx
		jp	sample0only


sample0only:				; CODE XREF: EntryPoint+61j
					; EntryPoint+146j ...
		ld	a, e
		or	d
		jr	z, sample0bankdone_solo

		ld	a, (bc)
		ld	l, a
		dec	de
		inc	bc
		exx
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		exx
		ld	a, (bc)
		exx
		ld	a, 80h
		dec	bc
		inc	bc

loc_116:				; DATA XREF: zMakeBankSwitch0+3w
		ld	(hl), 0

loc_118:				; DATA XREF: zMakeBankSwitch0+Aw
		ld	(hl), 0

loc_11A:				; DATA XREF: zMakeBankSwitch0+11w
		ld	(hl), 0

loc_11C:				; DATA XREF: zMakeBankSwitch0+18w
		ld	(hl), 0

loc_11E:				; DATA XREF: zMakeBankSwitch0+1Fw
		ld	(hl), 0

loc_120:				; DATA XREF: zMakeBankSwitch0+26w
		ld	(hl), 0

loc_122:				; DATA XREF: zMakeBankSwitch0+2Dw
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		exx
		add	a, l
		rra
		ex	af, af'
		ld	l, 0
		ld	(fm_in_progress_flag), a


busywait_2:				; CODE XREF: EntryPoint+133j
		bit	7, (hl)
		jr	nz, busywait_2

		ld	(hl), a
		ex	af, af'
		inc	hl
		ld	(hl), a
		xor	a
		ld	(fm_in_progress_flag), a
		ld	a, 3


pitchloop_1:				; CODE XREF: EntryPoint+140j
		dec	a
		jr	nz, pitchloop_1

		ld	a, (driver_input)
		or	a
		jp	p, sample0only

		jp	PCMplayloop

; ---------------------------------------------------------------------------

sample0bankdone_solo:			; CODE XREF: EntryPoint+F6j
		ld	ix, sample0
		ld	a, (ix+sample_entry.length_low_word)
		or	(ix+ sample_entry.length_low_word+1 )
		jr	z, sample0done_solo

		call	DoNextSampleBank

		call	zMakeBankSwitch0

		jp	sample0only

; ---------------------------------------------------------------------------

sample0done_solo:			; CODE XREF: EntryPoint+156j
		ld	(ix+sample_entry.playing), a
		jp	disable_dac

; ---------------------------------------------------------------------------

nosample0loop:				; CODE XREF: EntryPoint+5Aj
					; EntryPoint+D4j ...
		exx
		ld	a, (bc)
		exx
		ld	a, 80h
		ld	l, a
		dec	bc
		inc	bc
		exx

loc_170:				; DATA XREF: zMakeBankSwitch1+3w
		ld	(hl), 0

loc_172:				; DATA XREF: zMakeBankSwitch1+Aw
		ld	(hl), 0

loc_174:				; DATA XREF: zMakeBankSwitch1+11w
		ld	(hl), 0

loc_176:				; DATA XREF: zMakeBankSwitch1+18w
		ld	(hl), 0

loc_178:				; DATA XREF: zMakeBankSwitch1+1Fw
		ld	(hl), 0

loc_17A:				; DATA XREF: zMakeBankSwitch1+26w
		ld	(hl), 0

loc_17C:				; DATA XREF: zMakeBankSwitch1+2Dw
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	a, e
		or	d
		jr	z, sample1bankdone_solo

		ld	a, (bc)
		dec	de
		inc	bc
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		ld	(hl), 0
		exx
		add	a, l
		rra
		ex	af, af'
		ld	l, 0
		ld	(fm_in_progress_flag), a


busywait_3:				; CODE XREF: EntryPoint+1A6j
		bit	7, (hl)
		jr	nz, busywait_3

		ld	(hl), a
		ex	af, af'
		inc	hl
		ld	(hl), a
		xor	a
		ld	(fm_in_progress_flag), a
		ld	a, 3


pitchloop_2:				; CODE XREF: EntryPoint+1B3j
		dec	a
		jr	nz, pitchloop_2

		ld	a, (driver_input)
		or	a
		jp	p, nosample0loop

		jp	PCMplayloop

; ---------------------------------------------------------------------------

sample1bankdone_solo:			; CODE XREF: EntryPoint+184j
		ld	ix, sample1
		ld	a, (ix+sample_entry.length_low_word)
		or	(ix+ sample_entry.length_low_word+1 )
		jr	z, sample1done_solo

		call	DoNextSampleBank

		call	zMakeBankSwitch1

		exx
		jp	nosample0loop

; ---------------------------------------------------------------------------

sample1done_solo:			; CODE XREF: EntryPoint+1C9j
		ld	(ix+sample_entry.playing), a
		exx


disable_dac:				; CODE XREF: EntryPoint+164j
		ld	a, 80h
		ld	(fm_in_progress_flag), a


busywait_4:				; CODE XREF: EntryPoint+1E2j
		ld	a, (zYM2612_A0)
		or	a
		jp	m, busywait_4

		ld	a, 2Bh
		ld	(zYM2612_A0), a
		xor	a
		ld	(zYM2612_D0), a
		ld	(fm_in_progress_flag), a
		jp	PCMwaitloop

; End of function EntryPoint


; =============== S U B	R O U T	I N E =======================================


LoadSampleData:				; CODE XREF: EntryPoint+3Cp
					; EntryPoint+47p
		ld	a, (ix+sample_entry.id)
		or	a
		ret	z
		and	7Fh
		jp	nz, load_default_pcm

		ld	(ix+sample_entry.id), a
		ld	d, (ix+sample_entry.length)
		ld	e, (ix+	sample_entry.length+1 )
		ld	b, (ix+sample_entry.offset)
		ld	c, (ix+	sample_entry.offset+1 )
		ret

; ---------------------------------------------------------------------------

load_default_pcm:			; CODE XREF: LoadSampleData+7j
		dec	a
		ld	iy, BuiltinPCMList
		add	a, a
		add	a, a
		add	a, a
		ld	c, a
		ld	b, 0
		add	iy, bc
		ld	e, (iy+builtin_sample_entry.length)
		ld	d, (iy+	builtin_sample_entry.length+1 )
		ld	c, (iy+builtin_sample_entry)
		ld	b, (iy+	builtin_sample_entry.offset+1 )
		xor	a
		ld	(ix+sample_entry.id), a
		ret

; End of function LoadSampleData


; =============== S U B	R O U T	I N E =======================================


DoNextSampleBank:			; CODE XREF: EntryPoint+C8p
					; EntryPoint+E3p ...
		inc	(ix+sample_entry.bank)
		ld	bc, zROMWindow
		ld	a, (ix+sample_entry.length_low_word)
		rla
		ld	a, (ix+sample_entry.length_high_byte)
		rl	a
		jr	z, do_last_bank

		ld	a, (ix+sample_entry.length_low_word)
		sub	80h
		ld	(ix+sample_entry.length_low_word), a
		ld	a, (ix+sample_entry.length_high_byte)
		sbc	a, 0
		ld	(ix+sample_entry.length_high_byte), a
		ld	de, zROMWindow
		ret

; ---------------------------------------------------------------------------

do_last_bank:				; CODE XREF: DoNextSampleBank+Fj
		ld	d, (ix+sample_entry.length_low_word)
		ld	e, (ix+	sample_entry.length_low_word+1 )
		ld	(ix+sample_entry.length_low_word), 0
		ld	(ix+ sample_entry.length_low_word+1 ), 0
		ret

; End of function DoNextSampleBank


; =============== S U B	R O U T	I N E =======================================


zBankSwitch0:				; CODE XREF: EntryPoint+50p
		ld	a, (sample0.bank)
		ld	(hl), a
		rrca
		ld	(hl), a
		rrca
		ld	(hl), a
		rrca
		ld	(hl), a
		rrca
		ld	(hl), a
		rrca
		ld	(hl), a
		rrca
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	(hl), a
		ret

; End of function zBankSwitch0


; =============== S U B	R O U T	I N E =======================================


zMakeBankSwitch0:			; CODE XREF: EntryPoint+3Fp
					; EntryPoint+CBp ...
		ld	a, (sample0.bank)
		ld	(loc_116+1), a
		ld	(loc_86+1), a
		rrca
		ld	(loc_118+1), a
		ld	(loc_88+1), a
		rrca
		ld	(loc_11A+1), a
		ld	(loc_8A+1), a
		rrca
		ld	(loc_11C+1), a
		ld	(loc_8C+1), a
		rrca
		ld	(loc_11E+1), a
		ld	(loc_8E+1), a
		rrca
		ld	(loc_120+1), a
		ld	(loc_90+1), a
		rrca
		ld	(loc_122+1), a
		ld	(loc_92+1), a
		ret

; End of function zMakeBankSwitch0


; =============== S U B	R O U T	I N E =======================================


zMakeBankSwitch1:			; CODE XREF: EntryPoint+4Ap
					; EntryPoint+E6p ...
		ld	a, (sample1.bank)
		ld	(loc_170+1), a
		ld	(loc_6D+1), a
		rrca
		ld	(loc_172+1), a
		ld	(loc_6F+1), a
		rrca
		ld	(loc_174+1), a
		ld	(loc_71+1), a
		rrca
		ld	(loc_176+1), a
		ld	(loc_73+1), a
		rrca
		ld	(loc_178+1), a
		ld	(loc_75+1), a
		rrca
		ld	(loc_17A+1), a
		ld	(loc_77+1), a
		rrca
		ld	(loc_17C+1), a
		ld	(loc_79+1), a
		ret

; End of function zMakeBankSwitch1

; ---------------------------------------------------------------------------
BuiltinPCMList:	builtin_sample_entry <PCM0, 348h, 0, 0>	; DATA XREF: LoadSampleData+1Bo
		builtin_sample_entry <PCM1, 2C0h, 0, 0>
		builtin_sample_entry <PCM2, 190h, 0, 0>
		builtin_sample_entry <PCM3, 96Bh, 0, 0>
		builtin_sample_entry <PCM4, 254h, 0, 0>
PCM0:		db  7Fh, 80h, 80h, 7Fh,	80h, 80h, 7Eh, 80h, 82h, 76h, 68h, 7Dh,	90h, 78h, 6Ch, 7Dh
					; DATA XREF: ROM:BuiltinPCMListo
		db  7Fh, 7Bh, 76h, 6Bh,	78h, 75h, 41h, 3Ah, 56h, 22h,	0, 26h,	4Fh, 60h,0BAh,0FFh
		db 0FFh,0FAh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FDh,0FFh,0FFh,0E7h,0ABh, 86h, 57h
		db  12h,   0,	1,   1,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   7, 1Fh, 43h, 6Dh, 9Ah,0C9h,0F2h,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FEh
		db 0FFh,0FFh,0E5h,0B2h,	86h, 56h, 28h, 0Eh,   2,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  1, 18h, 37h, 59h
		db  82h,0A4h,0BEh,0E2h,0FEh,0FFh,0FEh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FDh,0ECh,0DCh,0CDh,0B6h, 9Dh, 87h, 6Dh, 4Dh, 27h,   9,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0, 0Ch,	24h, 39h, 4Bh, 60h
		db  6Eh, 6Fh, 7Ah, 91h,	9Eh,0A5h,0B1h,0BFh,0D0h,0E4h,0F4h,0FEh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0ECh,0D1h,0BAh,0A3h, 84h, 63h, 47h, 29h, 0Ah,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db  0Bh, 27h, 45h, 6Ah,	8Ah, 9Eh,0B5h,0D0h,0E6h,0F7h,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FEh,0F7h,0E7h,0D1h,0BCh,0ABh, 9Ch, 8Bh,	79h, 66h, 50h, 34h
		db  15h,   2,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	2, 18h,	33h, 50h, 73h, 93h
		db 0B2h,0D0h,0DDh,0E6h,0F9h,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FBh,0F4h,0F2h,0F6h,0FCh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FEh,0EEh,0DAh,0C7h,0B2h,	97h, 7Ch, 6Bh, 65h
		db  55h, 38h, 27h, 27h,	1Bh,   5,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  2, 0Eh, 1Bh, 2Eh
		db  46h, 5Eh, 72h, 86h,	9Ah,0ADh,0C2h,0D6h,0E5h,0F4h,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FAh,0F0h,0E8h,0DDh,0D0h,0C4h,0BAh,0AFh,0A5h, 9Eh, 9Ah,	95h, 8Ch, 81h, 78h
		db  71h, 67h, 58h, 4Eh,	46h, 39h, 30h, 29h, 20h, 17h, 0Eh,   5,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   1, 0Bh, 12h,	13h, 1Ch, 2Dh, 37h, 3Dh, 49h, 59h, 68h,	72h, 77h, 82h, 96h
		db 0A2h,0A8h,0B6h,0C5h,0CEh,0DAh,0E8h,0F1h,0F9h,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FBh
		db 0F0h,0E4h,0D9h,0CFh,0C5h,0B9h,0ADh, 9Fh, 93h, 8Ch, 7Dh, 68h,	61h, 5Ch, 47h, 36h
		db  36h, 30h, 20h, 15h,	10h, 0Bh,   9,	 6,   2,   3,	5,   4,	  4,   4,   4,	 5
		db    5,   5,	5,   6,	  6,   6,   6,	 7,   7,   7, 0Eh, 17h,	19h, 1Ch, 27h, 33h
		db  35h, 38h, 43h, 4Eh,	50h, 55h, 62h, 6Eh, 73h, 74h, 7Ah, 85h,	8Dh, 8Fh, 90h, 96h
		db  9Eh,0A0h, 99h, 9Ah,0A0h, 9Dh, 98h, 99h, 9Bh, 98h, 97h, 98h,	99h, 9Dh, 9Dh, 9Eh
		db 0A1h,0A3h,0A4h,0A6h,0A7h,0A8h,0A9h,0A9h,0ABh,0B0h,0B1h,0AEh,0B0h,0B1h,0B0h,0B1h
		db 0B1h,0B0h,0B2h,0B2h,0AFh,0B1h,0B4h,0B2h,0AEh,0B1h,0B4h,0B2h,0AEh,0ACh,0ABh,0AAh
		db 0A6h,0A2h,0A0h, 9Fh,	9Ch, 99h, 95h, 91h, 8Eh, 8Bh, 88h, 87h,	84h, 7Ch, 77h, 76h

		db  74h, 70h, 6Eh, 6Ch,	6Ah, 69h, 67h, 65h, 66h, 68h, 68h, 66h,	68h, 6Ch, 6Ch, 6Bh
		db  6Fh, 72h, 71h, 71h,	73h, 74h, 75h, 75h, 76h, 76h, 76h, 77h,	7Ah, 7Ah, 79h, 7Ah
		db  79h, 78h, 78h, 78h,	76h, 76h, 76h, 75h, 71h, 6Fh, 6Fh, 6Eh,	6Ch, 6Bh, 6Ah, 6Bh
		db  6Ah, 68h, 67h, 69h,	69h, 6Ah, 6Bh, 6Ch, 6Eh, 6Fh, 6Fh, 71h,	72h, 73h, 74h, 75h
		db  77h, 78h, 79h, 7Bh,	7Dh, 7Eh, 7Fh, 81h, 82h, 84h, 84h, 84h,	85h, 86h, 85h, 85h
		db  86h, 87h, 86h, 85h,	85h, 85h, 86h, 85h, 84h, 84h, 84h, 84h,	84h, 84h, 84h, 84h
		db  84h, 84h, 84h, 84h,	83h, 84h, 84h, 84h, 83h, 84h, 84h, 84h,	84h, 84h, 84h, 84h
		db  84h, 84h, 85h, 85h,	85h, 85h, 84h, 84h, 84h, 84h, 84h, 84h,	84h, 83h, 83h, 82h
		db  82h, 82h, 82h, 81h,	81h, 81h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 7Fh
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
PCM1:		db  80h, 80h, 80h, 7Fh,	80h, 80h, 7Eh, 82h, 7Fh, 79h, 90h, 83h,	65h,0BDh,0C8h, 4Dh
					; DATA XREF: ROM:BuiltinPCMListo
		db  8Dh,0DEh, 5Fh, 4Bh,0E8h,0FFh,0FFh,0DCh, 9Ah,0ADh,0CFh, 8Ah,	2Ah, 23h, 35h, 13h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0, 32h, 5Bh, 9Ah,0E7h,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0F4h,0B3h, 7Ah,	41h, 11h,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	4, 25h,	47h, 67h, 87h,0A9h,0C3h,0DBh,0F5h,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0F5h,0E0h,0D1h,0BFh,0ABh, 9Ah, 8Ah, 7Ah
		db  6Ch, 5Fh, 52h, 45h,	35h, 27h, 1Bh, 12h, 0Ah,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0, 0Ch, 1Dh, 31h,	42h, 50h, 5Fh, 70h, 80h, 8Ch, 97h,0A3h,0AEh,0BAh,0CAh,0D8h
		db 0E4h,0EFh,0FAh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0F7h,0E9h,0E4h,0E0h,0D4h,0CBh
		db 0C7h,0C0h,0B6h,0AEh,0A9h,0A5h, 9Fh, 99h, 91h, 8Fh, 91h, 8Bh,	83h, 81h, 83h, 83h
		db  7Eh, 7Ah, 7Ch, 7Dh,	7Bh, 7Ah, 7Ah, 79h, 7Bh, 7Bh, 78h, 76h,	73h, 71h, 6Fh, 6Ch
		db  6Bh, 6Ah, 66h, 61h,	5Dh, 5Eh, 5Ch, 58h, 55h, 53h, 52h, 50h,	4Dh, 4Ch, 47h, 42h
		db  41h, 41h, 3Dh, 39h,	3Bh, 39h, 35h, 35h, 35h, 35h, 34h, 33h,	33h, 32h, 32h, 33h
		db  32h, 31h, 32h, 34h,	35h, 35h, 34h, 35h, 36h, 37h, 36h, 35h,	35h, 34h, 33h, 32h
		db  32h, 32h, 33h, 33h,	33h, 33h, 34h, 34h, 36h, 38h, 38h, 3Ah,	3Ch, 3Eh, 40h, 43h
		db  46h, 48h, 4Ah, 4Dh,	4Fh, 53h, 57h, 5Bh, 5Dh, 61h, 66h, 6Ah,	6Ch, 71h, 77h, 7Ch
		db  80h, 85h, 8Ch, 93h,	97h, 9Dh,0A3h,0A7h,0ACh,0B2h,0B6h,0BAh,0C0h,0C4h,0C7h,0CAh
		db 0CFh,0D2h,0D4h,0D7h,0D9h,0DBh,0DDh,0DEh,0DFh,0E1h,0E2h,0E0h,0E1h,0E1h,0DFh,0DEh
		db 0DEh,0DCh,0DAh,0D8h,0D6h,0D3h,0D0h,0CDh,0CAh,0C6h,0C4h,0C1h,0BCh,0B7h,0B3h,0AEh
		db 0AAh,0A6h,0A2h, 9Ch,	98h, 96h, 90h, 8Bh, 87h, 84h, 82h, 7Ch,	79h, 79h, 74h, 70h
		db  70h, 6Eh, 6Ah, 6Ah,	69h, 66h, 64h, 63h, 63h, 64h, 61h, 60h,	62h, 62h, 61h, 61h
		db  62h, 63h, 64h, 64h,	64h, 65h, 66h, 66h, 68h, 6Ah, 69h, 6Ah,	6Ch, 6Bh, 6Bh, 6Ch
		db  6Eh, 6Eh, 6Dh, 6Ch,	6Dh, 70h, 70h, 6Eh, 70h, 71h, 70h, 72h,	72h, 71h, 73h, 75h
		db  74h, 74h, 75h, 76h,	76h, 75h, 75h, 75h, 75h, 74h, 73h, 73h,	72h, 72h, 72h, 70h
		db  70h, 70h, 6Fh, 6Dh,	6Dh, 6Eh, 6Dh, 6Bh, 6Bh, 6Ah, 69h, 69h,	69h, 68h, 68h, 68h
		db  67h, 67h, 67h, 66h,	67h, 67h, 66h, 66h, 67h, 68h, 68h, 68h,	69h, 6Ah, 6Bh, 6Ah
		db  6Bh, 6Bh, 6Ch, 6Dh,	6Dh, 6Eh, 6Fh, 70h, 70h, 71h, 72h, 73h,	74h, 75h, 76h, 77h
		db  78h, 79h, 7Ah, 7Bh,	7Bh, 7Dh, 7Eh, 7Fh, 7Fh, 80h, 81h, 82h,	83h, 83h, 85h, 86h
		db  86h, 86h, 87h, 87h,	88h, 8Ah, 8Ah, 8Bh, 8Bh, 8Bh, 8Ah, 8Ah,	8Bh, 8Bh, 8Bh, 8Ah
		db  8Ah, 8Ah, 8Bh, 8Bh,	8Ah, 8Ah, 8Ah, 8Ah, 8Ah, 8Ah, 8Ah, 8Ah,	89h, 89h, 89h, 89h
		db  89h, 88h, 87h, 88h,	86h, 81h, 7Fh, 80h, 80h, 7Fh, 80h, 80h,	7Fh, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
PCM2:		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 7Fh, 7Fh, 80h, 7Fh, 80h,	80h, 7Ch, 87h, 7Dh
					; DATA XREF: ROM:BuiltinPCMListo
		db  88h,0BFh,0BFh,0BFh,0BFh,0BFh,0B0h, 4Dh, 40h, 40h, 40h, 40h,	40h, 40h, 40h, 40h
		db  40h,0A7h, 81h, 8Ch,0BFh,0BFh,0BFh,0BFh,0BCh,0BFh,0BFh,0BFh,0BFh,0BFh,0BBh, 9Eh
		db  9Fh,0BFh, 9Ch,0A3h,0BFh, 87h, 93h, 7Ah, 40h, 40h, 40h, 40h,	40h, 40h, 40h, 40h
		db  40h, 40h, 40h, 40h,	40h, 40h, 40h, 40h, 40h, 40h, 40h, 5Ch,	9Eh,0BFh,0BFh,0BFh
		db 0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0B8h,0A6h, 90h, 73h
		db  81h, 6Fh, 4Dh, 5Dh,	55h, 40h, 40h, 40h, 40h, 40h, 40h, 40h,	42h, 43h, 4Eh, 6Fh
		db  86h,0A6h,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh,0BFh, 8Dh,0A5h
		db 0B6h,0A6h,0B1h, 91h,	7Dh, 77h, 68h, 79h, 69h, 47h, 55h, 49h,	40h, 46h, 4Ah, 40h
		db  4Ah, 58h, 53h, 45h,	40h, 48h, 5Ah, 59h, 4Ch, 45h, 4Bh, 44h,	45h, 5Ch, 72h, 7Ch
		db  8Fh,0B2h,0BBh,0B4h,0BBh,0BBh,0BAh,0B9h,0BAh,0B4h, 8Eh, 7Eh,	7Fh, 78h, 76h, 77h
		db  72h, 71h, 72h, 6Eh,	64h, 65h, 6Ch, 5Dh, 56h, 5Fh, 5Fh, 50h,	4Ah, 5Eh, 64h, 4Ah
		db  51h, 6Fh, 67h, 76h,	88h, 79h, 8Ch,0A8h, 96h, 91h, 9Fh,0A5h,	9Ch, 90h, 98h, 8Fh
		db  8Bh, 9Bh, 90h, 89h,	9Eh, 95h, 81h, 8Ch, 92h, 8Ah, 85h, 7Ch,	79h, 87h, 8Ch, 70h
		db  61h, 7Ah, 7Eh, 6Eh,	70h, 76h, 73h, 74h, 7Fh, 80h, 71h, 71h,	7Ch, 76h, 6Fh, 72h
		db  70h, 7Ch, 7Fh, 75h,	7Fh, 88h, 88h, 8Ch, 94h, 9Ah, 97h, 90h,	95h, 98h, 8Dh, 89h
		db  8Ah, 84h, 85h, 80h,	7Dh, 83h, 79h, 79h, 83h, 80h, 80h, 7Eh,	7Dh, 81h, 7Ah, 75h
		db  79h, 7Ch, 79h, 72h,	72h, 77h, 75h, 79h, 7Bh, 76h, 7Ah, 7Ah,	7Ch, 86h, 86h, 81h
		db  87h, 89h, 81h, 82h,	84h, 83h, 88h, 7Ch, 7Eh, 8Eh, 7Dh, 81h,	8Ch, 7Fh, 84h, 88h
		db  81h, 83h, 85h, 7Bh,	7Ch, 81h, 7Bh, 7Eh, 80h, 7Eh, 7Dh, 7Ah,	80h, 80h, 7Dh, 7Fh
		db  7Dh, 7Eh, 7Fh, 7Eh,	7Ch, 7Eh, 7Fh, 7Dh, 7Fh, 7Fh, 7Fh, 7Eh,	7Fh, 82h, 82h, 80h
		db  81h, 85h, 84h, 84h,	83h, 7Fh, 7Eh, 7Dh, 7Ch, 7Ch, 7Bh, 7Ah,	7Bh, 7Eh, 7Eh, 7Dh
		db  7Dh, 82h, 83h, 82h,	82h, 85h, 84h, 82h, 85h, 85h, 83h, 83h,	81h, 80h, 81h, 81h
		db  7Eh, 7Eh, 7Eh, 7Dh,	7Ch, 7Dh, 7Eh, 7Dh, 7Dh, 80h, 7Fh, 7Eh,	80h, 7Fh, 7Fh, 7Fh
		db  7Fh, 7Fh, 7Fh, 7Fh,	7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 80h, 7Fh, 7Fh,	7Fh, 80h, 80h, 80h
PCM3:		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 7Fh, 7Fh, 80h, 80h,	80h, 80h, 7Fh, 7Ch
					; DATA XREF: ROM:BuiltinPCMListo
		db  77h, 71h, 69h, 5Dh,	48h, 30h, 26h,	 0,   0, 24h, 1Bh,   0,	  0,   0, 74h,0A8h
		db 0A0h,0FEh,0FFh,0DFh,0FFh,0FFh,0FFh,0F8h,0FBh,0E5h,0C0h, 91h,	70h, 55h, 33h, 1Ch
		db    1,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   3, 2Bh, 5Bh
		db  81h,0ACh,0F2h,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0BFh, 9Bh, 64h,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   6, 25h
		db  29h, 3Ah, 63h, 7Dh,	77h, 85h,0A8h,0ACh,0AAh,0B6h,0A9h, 9Eh,0AEh,0ACh, 94h, 84h
		db  7Eh, 77h, 61h, 4Ah,	45h, 4Ah, 44h, 2Fh, 2Bh, 3Ch, 3Ah, 30h,	30h, 35h, 3Eh, 40h
		db  39h, 43h, 58h, 6Ah,	7Bh, 84h, 8Bh, 99h,0B6h,0D7h,0E0h,0EAh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0F7h,0E9h,0DCh,0C2h, 9Eh, 81h
		db  75h, 6Ah, 4Fh, 31h,	1Eh, 0Eh,   1,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   9,	7, 14h,	34h, 51h, 5Ch, 69h, 83h, 9Bh,0B1h,0C1h,0C5h,0DDh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FAh,0F0h,0DFh,0BFh,0B8h,0B9h, 98h, 7Eh, 79h, 6Ah, 57h, 43h,	2Eh, 22h, 19h,	 2
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db  0Fh, 29h, 2Dh, 30h,	4Bh, 5Ch, 59h, 64h, 73h, 6Eh, 72h, 89h,	92h, 8Dh, 8Ah, 8Ch
		db  96h, 9Eh, 97h, 9Ah,0ADh,0ABh, 9Ah, 9Ch,0AAh,0ADh,0A6h,0A5h,0ACh,0B0h,0B4h,0BEh
		db 0C2h,0BDh,0C7h,0DDh,0E2h,0E0h,0EBh,0F6h,0F6h,0F9h,0FFh,0FEh,0EDh,0EDh,0FEh,0FBh
		db 0F1h,0F9h,0F5h,0DEh,0D6h,0D8h,0CDh,0C0h,0BBh,0B2h, 9Fh, 8Eh,	88h, 7Bh, 5Dh, 49h
		db  44h, 39h, 29h, 15h,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db  0Ah, 20h, 30h, 3Eh,	4Eh, 6Bh, 8Ah, 9Ah,0AAh,0C3h,0D6h,0E4h,0F2h,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0ECh,0D9h,0D3h,0C5h
		db 0B3h,0A8h, 9Ah, 8Bh,	81h, 72h, 5Fh, 58h, 56h, 42h, 2Fh, 31h,	2Ah, 0Fh,   3, 0Ah
		db    7,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    2,   1,	2, 12h,	1Dh, 1Ah, 1Eh, 31h, 3Bh, 3Bh, 44h, 5Ah,	66h, 66h, 74h, 8Bh
		db  97h, 9Ah,0A4h,0B7h,0C6h,0CFh,0D9h,0E6h,0F2h,0FCh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0EFh,0E5h,0DDh,0D2h
		db 0C5h,0B5h,0A6h, 9Ch,	90h, 7Dh, 6Dh, 64h, 55h, 40h, 35h, 2Fh,	23h, 15h,   9,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   4,   6, 16h, 1Dh,	1Ah, 27h, 3Bh, 3Eh
		db  3Eh, 4Bh, 56h, 5Fh,	6Dh, 7Bh, 82h, 88h, 90h, 98h,0A5h,0ABh,0A7h,0AFh,0BCh,0B7h
		db 0ABh,0B0h,0B8h,0B3h,0B2h,0B7h,0B4h,0AEh,0ABh,0AAh,0ADh,0A9h,0A1h,0A7h,0AFh,0A1h
		db  99h,0A4h,0A2h, 9Fh,0AAh,0A9h, 9Dh,0A4h,0B0h,0ABh,0AEh,0BAh,0C2h,0C7h,0C9h,0CDh
		db 0D3h,0D8h,0DAh,0DCh,0DFh,0E3h,0E2h,0E1h,0E5h,0E4h,0DEh,0E1h,0EAh,0E7h,0E4h,0E9h
		db 0E9h,0E7h,0E6h,0E1h,0E1h,0E4h,0DDh,0D5h,0D5h,0D5h,0CEh,0C0h,0BAh,0BCh,0B6h,0AAh
		db 0A8h,0A8h,0A3h, 9Eh,	98h, 91h, 8Dh, 8Dh, 8Ch, 84h, 7Eh, 7Bh,	76h, 6Fh, 69h, 67h
		db  60h, 5Ah, 5Ah, 57h,	54h, 55h, 51h, 49h, 43h, 46h, 4Ah, 40h,	30h, 39h, 41h, 2Dh
		db  25h, 31h, 2Bh, 1Dh,	23h, 26h, 19h, 19h, 25h, 24h, 1Bh, 1Bh,	1Fh, 1Dh, 13h, 17h
		db  24h, 22h, 18h, 18h,	1Dh, 1Dh, 1Ah, 1Bh, 23h, 29h, 23h, 22h,	2Bh, 2Dh, 2Ch, 34h
		db  3Ah, 36h, 36h, 42h,	4Ch, 48h, 46h, 56h, 66h, 64h, 64h, 72h,	7Ah, 79h, 80h, 8Ah
		db  90h, 95h, 90h, 94h,0A7h,0A7h,0A3h,0B5h,0BCh,0AEh,0AFh,0C1h,0C7h,0BFh,0BFh,0CEh
		db 0D0h,0C5h,0C9h,0D3h,0CFh,0CBh,0D4h,0D8h,0D9h,0DCh,0D7h,0D4h,0D4h,0CFh,0D1h,0D8h
		db 0D3h,0CCh,0CCh,0CDh,0C9h,0C2h,0C4h,0C4h,0B9h,0BFh,0CAh,0BCh,0B2h,0BEh,0C2h,0B9h
		db 0BAh,0BCh,0B7h,0B6h,0B7h,0B6h,0BAh,0B9h,0B9h,0BFh,0C0h,0B7h,0B1h,0B3h,0B4h,0AFh
		db 0AAh,0B0h,0B3h,0ADh,0AAh,0AAh,0AAh,0AEh,0ADh,0A5h,0A7h,0A8h,0A1h,0A4h,0A8h, 9Eh
		db  9Dh,0A1h, 9Ah, 98h,	9Eh, 9Ah, 93h, 96h, 98h, 94h, 8Dh, 84h,	85h, 89h, 81h, 7Eh
		db  80h, 71h, 5Ch, 5Ch,	60h, 55h, 44h, 3Fh, 3Fh, 37h, 2Bh, 22h,	17h, 18h, 1Ah,	 8
		db    0,   3,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0, 0Ch,	11h, 0Fh, 1Ah, 28h, 2Eh, 32h, 40h, 52h,	59h, 60h, 72h, 7Ch
		db  7Dh, 8Ch, 9Eh,0A1h,0A6h,0B3h,0BCh,0C3h,0CDh,0DBh,0E1h,0DFh,0E3h,0EDh,0F1h,0F6h
		db 0FDh,0FEh,0FFh,0FFh,0FFh,0FEh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FEh,0FCh,0F8h,0F6h
		db 0F5h,0F0h,0EEh,0EFh,0E9h,0DEh,0D9h,0D6h,0D5h,0D3h,0CBh,0C7h,0C7h,0C1h,0BAh,0B5h
		db 0B2h,0B3h,0AEh,0A5h,0A6h,0A5h, 9Eh, 9Eh,0A0h, 9Eh, 9Eh, 99h,	93h, 91h, 8Eh, 89h
		db  86h, 85h, 83h, 80h,	7Fh, 77h, 74h, 73h, 6Dh, 6Fh, 73h, 69h,	5Fh, 5Fh, 5Eh, 5Ah
		db  55h, 52h, 57h, 57h,	51h, 50h, 50h, 4Ch, 4Bh, 4Bh, 48h, 45h,	46h, 49h, 43h, 38h
		db  39h, 40h, 3Ch, 36h,	37h, 34h, 2Eh, 29h, 2Bh, 34h, 31h, 28h,	2Ch, 34h, 33h, 32h
		db  38h, 39h, 37h, 3Eh,	47h, 49h, 4Ch, 53h, 59h, 5Dh, 5Fh, 65h,	6Dh, 6Dh, 6Fh, 7Bh
		db  82h, 7Eh, 7Fh, 8Ch,	93h, 8Eh, 8Ch, 96h, 9Eh, 99h, 95h, 9Ah,0A1h,0A0h, 9Eh,0A0h
		db 0A6h,0A7h,0A3h,0A2h,0A3h,0A2h,0A2h, 9Eh, 98h, 9Eh,0A0h, 94h,	8Dh, 93h, 8Fh, 86h
		db  85h, 84h, 81h, 81h,	80h, 7Bh, 7Dh, 7Fh, 7Ch, 7Dh, 81h, 82h,	7Fh, 81h, 8Ah, 8Fh
		db  8Dh, 8Eh, 92h, 99h,	9Ch,0A0h,0A9h,0AFh,0AFh,0B2h,0B9h,0C0h,0C6h,0C9h,0CCh,0D0h
		db 0D3h,0D4h,0DAh,0E3h,0E2h,0E0h,0E4h,0E7h,0EDh,0EFh,0E7h,0E6h,0EEh,0EAh,0E0h,0DEh
		db 0E0h,0DDh,0D5h,0CFh,0CCh,0C8h,0C0h,0B3h,0AAh,0A8h, 9Dh, 8Fh,	85h, 7Fh, 7Ah, 6Ch
		db  5Fh, 59h, 52h, 4Bh,	47h, 41h, 36h, 2Eh, 2Ah, 23h, 1Ch, 18h,	17h, 13h,   8,	 0
		db    5,   6,	0,   0,	  0,   0,   0,	 0,   0,   2,	0,   0,	  1,   7,   8,	 7
		db  0Dh, 14h, 17h, 1Ch,	20h, 26h, 30h, 35h, 35h, 3Eh, 4Eh, 53h,	53h, 61h, 6Ch, 6Dh
		db  76h, 80h, 86h, 8Eh,	94h, 98h, 9Dh, 9Fh,0A3h,0AEh,0B2h,0B0h,0B6h,0BEh,0BDh,0BBh
		db 0C0h,0C7h,0CAh,0CEh,0D4h,0D4h,0D2h,0D6h,0D8h,0D6h,0DCh,0E1h,0DFh,0DFh,0DFh,0DBh
		db 0DAh,0DCh,0D8h,0D1h,0D1h,0D1h,0CBh,0C6h,0C8h,0C7h,0C0h,0BEh,0BDh,0B8h,0B6h,0B3h
		db 0ADh,0ACh,0ACh,0A9h,0A8h,0AAh,0AAh,0A9h,0A4h,0A0h,0A3h,0A2h,	9Bh, 9Ah, 99h, 92h
		db  8Dh, 8Dh, 8Ah, 85h,	7Eh, 7Bh, 79h, 72h, 6Ah, 68h, 65h, 5Ch,	56h, 57h, 54h, 4Fh
		db  50h, 50h, 4Ah, 49h,	4Ah, 4Dh, 50h, 4Eh, 4Eh, 51h, 52h, 54h,	57h, 5Bh, 5Ch, 59h
		db  58h, 5Ah, 5Eh, 5Eh,	58h, 57h, 5Bh, 5Ah, 5Ah, 58h, 55h, 58h,	59h, 54h, 55h, 59h
		db  57h, 53h, 54h, 57h,	58h, 57h, 57h, 5Bh, 5Bh, 58h, 5Ah, 5Fh,	5Dh, 58h, 5Ah, 5Fh
		db  5Eh, 5Dh, 5Eh, 60h,	5Eh, 5Dh, 60h, 63h, 64h, 64h, 63h, 63h,	63h, 65h, 68h, 69h
		db  67h, 69h, 6Ah, 69h,	6Ah, 6Fh, 75h, 7Ah, 7Bh, 7Eh, 84h, 8Ah,	8Ch, 8Ch, 92h, 98h
		db  9Bh, 9Dh,0A3h,0A6h,0A8h,0ACh,0AEh,0B2h,0B6h,0B7h,0B7h,0B8h,0BAh,0BCh,0BDh,0BEh
		db 0BFh,0BEh,0BDh,0BDh,0BDh,0BDh,0BDh,0BAh,0BAh,0BCh,0B8h,0B5h,0B8h,0B6h,0B5h,0B5h
		db 0B1h,0AEh,0B2h,0B2h,0ACh,0AAh,0AAh,0A7h,0A1h, 9Fh,0A0h, 9Bh,	94h, 8Fh, 8Bh, 8Ch
		db  89h, 81h, 7Dh, 7Dh,	77h, 74h, 75h, 71h, 69h, 6Ah, 6Bh, 66h,	64h, 68h, 66h, 60h
		db  60h, 63h, 63h, 60h,	5Fh, 62h, 61h, 5Bh, 5Ah, 5Fh, 5Fh, 5Bh,	5Ch, 5Fh, 5Ch, 5Ah
		db  5Dh, 5Eh, 5Ch, 5Bh,	5Eh, 61h, 64h, 64h, 66h, 6Ch, 6Eh, 6Ah,	6Eh, 76h, 76h, 75h
		db  78h, 7Ah, 7Ah, 79h,	7Bh, 7Dh, 7Bh, 78h, 79h, 7Ah, 78h, 76h,	75h, 76h, 74h, 72h
		db  74h, 72h, 6Eh, 6Fh,	70h, 6Eh, 6Dh, 70h, 70h, 6Fh, 72h, 73h,	70h, 74h, 79h, 78h
		db  77h, 78h, 7Bh, 7Dh,	7Ch, 7Bh, 7Dh, 7Ch, 7Ah, 7Ch, 7Eh, 7Bh,	7Ch, 7Eh, 7Dh, 7Bh
		db  7Eh, 7Eh, 7Ch, 7Dh,	80h, 80h, 7Bh, 7Bh, 82h, 84h, 80h, 80h,	83h, 81h, 80h, 84h
		db  84h, 7Fh, 80h, 84h,	83h, 81h, 82h, 83h, 83h, 84h, 85h, 84h,	84h, 84h, 84h, 85h
		db  87h, 87h, 88h, 88h,	88h, 89h, 89h, 8Bh, 8Ch, 8Bh, 8Ch, 8Dh,	8Dh, 8Eh, 91h, 91h
		db  90h, 90h, 91h, 93h,	92h, 91h, 93h, 94h, 93h, 92h, 93h, 94h,	95h, 95h, 94h, 94h
		db  94h, 93h, 94h, 94h,	92h, 95h, 96h, 94h, 93h, 93h, 91h, 8Fh,	8Fh, 90h, 8Dh, 89h
		db  8Ah, 89h, 84h, 82h,	82h, 80h, 80h, 7Dh, 79h, 78h, 78h, 75h,	72h, 71h, 71h, 71h
		db  70h, 6Fh, 6Dh, 6Bh,	6Ch, 6Ch, 6Ah, 6Bh, 6Dh, 6Bh, 6Ah, 6Ch,	6Bh, 69h, 6Bh, 6Dh
		db  6Dh, 6Bh, 6Bh, 6Dh,	6Dh, 6Dh, 6Eh, 6Fh, 6Eh, 6Dh, 70h, 72h,	70h, 70h, 71h, 73h
		db  74h, 74h, 75h, 77h,	78h, 7Ch, 7Eh, 7Bh, 7Ah, 80h, 80h, 7Dh,	7Eh, 82h, 81h, 82h
		db  84h, 84h, 83h, 83h,	84h, 85h, 86h, 85h, 85h, 84h, 83h, 83h,	83h, 83h, 82h, 82h
		db  83h, 82h, 80h, 81h,	82h, 80h, 80h, 81h, 82h, 7Fh, 7Eh, 80h,	80h, 7Fh, 80h, 7Fh
		db  7Eh, 7Fh, 80h, 7Fh,	7Fh, 7Fh, 81h, 81h, 80h, 80h, 82h, 81h,	7Eh, 7Eh, 7Fh, 7Dh
		db  7Ch, 7Bh, 79h, 78h,	77h, 75h, 75h, 75h, 74h, 72h, 70h, 71h,	71h, 6Fh, 6Dh, 6Eh
		db  70h, 70h, 6Eh, 6Fh,	72h, 72h, 71h, 73h, 76h, 76h, 76h, 77h,	7Ah, 7Dh, 7Bh, 7Bh
		db  7Eh, 80h, 7Fh, 7Eh,	7Fh, 82h, 84h, 84h, 83h, 84h, 85h, 86h,	89h, 89h, 89h, 8Ah
		db  8Dh, 90h, 90h, 90h,	93h, 97h, 98h, 9Ah, 9Dh, 9Eh, 9Eh,0A0h,0A2h,0A3h,0A3h,0A4h
		db 0A6h,0A7h,0A6h,0A5h,0A4h,0A4h,0A4h,0A2h,0A0h, 9Fh, 9Eh, 9Ch,	9Ch, 99h, 97h, 96h
		db  94h, 91h, 8Fh, 8Ch,	8Ch, 8Ah, 88h, 85h, 83h, 82h, 80h, 7Dh,	7Dh, 7Eh, 7Bh, 77h
		db  79h, 79h, 75h, 74h,	75h, 74h, 72h, 71h, 71h, 71h, 70h, 6Eh,	6Eh, 6Eh, 6Eh, 6Eh
		db  6Dh, 6Bh, 6Ch, 6Bh,	6Ah, 6Bh, 6Bh, 6Bh, 6Bh, 6Bh, 6Ch, 6Eh,	6Dh, 6Ah, 6Ch, 6Fh
		db  6Dh, 6Dh, 6Fh, 71h,	71h, 71h, 71h, 71h, 74h, 76h, 77h, 76h,	77h, 79h, 7Ah, 7Bh
		db  7Dh, 7Fh, 80h, 81h,	81h, 83h, 84h, 84h, 85h, 86h, 87h, 88h,	87h, 88h, 89h, 89h
		db  88h, 89h, 89h, 87h,	85h, 85h, 85h, 84h, 80h, 7Fh, 7Fh, 7Dh,	7Ah, 78h, 77h, 74h
		db  72h, 70h, 6Fh, 6Dh,	6Bh, 6Bh, 68h, 64h, 63h, 64h, 63h, 61h,	60h, 61h, 60h, 5Dh
		db  5Dh, 5Fh, 5Eh, 5Eh,	5Fh, 5Fh, 5Eh, 5Dh, 5Eh, 5Fh, 5Eh, 5Eh,	5Fh, 5Eh, 5Ch, 5Ch
		db  5Dh, 5Dh, 5Dh, 5Eh,	5Eh, 5Fh, 60h, 61h, 62h, 63h, 64h, 66h,	68h, 69h, 6Ch, 6Eh
		db  6Fh, 72h, 76h, 7Ah,	7Ch, 7Fh, 81h, 83h, 86h, 8Ah, 8Ch, 8Eh,	92h, 95h, 98h, 99h
		db  9Ch, 9Fh,0A2h,0A5h,0A7h,0A8h,0ABh,0ADh,0AEh,0AFh,0B2h,0B5h,0B6h,0B8h,0BAh,0BCh
		db 0BCh,0BDh,0C0h,0C3h,0C3h,0C3h,0C5h,0C6h,0C7h,0C7h,0C7h,0C8h,0C8h,0C7h,0C6h,0C6h
		db 0C4h,0C4h,0C3h,0C0h,0BDh,0BBh,0B7h,0B3h,0B0h,0ADh,0A8h,0A4h,0A2h, 9Eh, 98h, 94h
		db  92h, 8Dh, 89h, 87h,	82h, 7Ch, 79h, 78h, 73h, 6Fh, 6Eh, 6Ch,	69h, 65h, 62h, 61h
		db  5Fh, 5Bh, 5Ah, 59h,	56h, 54h, 54h, 52h, 50h, 4Fh, 4Eh, 4Dh,	4Ch, 4Ch, 4Ah, 49h
		db  49h, 48h, 49h, 49h,	47h, 47h, 49h, 4Ah, 49h, 49h, 49h, 4Bh,	4Bh, 4Bh, 4Ch, 4Eh
		db  4Eh, 4Eh, 50h, 50h,	50h, 51h, 54h, 56h, 57h, 58h, 58h, 5Ah,	5Eh, 5Fh, 60h, 62h
		db  66h, 68h, 67h, 69h,	6Eh, 70h, 71h, 73h, 77h, 79h, 7Bh, 7Eh,	80h, 82h, 85h, 87h
		db  89h, 8Ch, 8Fh, 8Fh,	91h, 94h, 96h, 97h, 98h, 99h, 9Ah, 9Bh,	9Ch, 9Ch, 9Dh, 9Eh
		db  9Eh, 9Dh, 9Eh, 9Fh,	9Dh, 9Ch, 9Dh, 9Eh, 9Bh, 9Ah, 9Bh, 9Bh,	99h, 98h, 97h, 97h
		db  95h, 94h, 94h, 93h,	91h, 90h, 91h, 8Fh, 8Dh, 8Eh, 8Eh, 8Ch,	8Bh, 8Bh, 8Bh, 8Ah
		db  87h, 87h, 88h, 87h,	85h, 84h, 84h, 83h, 82h, 81h, 80h, 80h,	7Fh, 7Fh, 7Fh, 7Eh
		db  7Dh, 7Eh, 7Dh, 7Ah,	7Bh, 7Ch, 7Ah, 79h, 79h, 7Bh, 7Ah, 7Ah,	7Ah, 79h, 7Ah, 7Bh
		db  7Bh, 7Bh, 7Ch, 7Ch,	7Ch, 7Ch, 7Ch, 7Dh, 7Dh, 7Eh, 7Eh, 7Eh,	7Eh, 80h, 80h, 7Fh
		db  7Fh, 82h, 81h, 80h,	81h, 81h, 80h, 80h, 7Fh, 80h, 80h, 7Fh,	7Fh, 7Fh, 7Fh, 7Fh
		db  7Fh, 7Fh, 80h, 7Fh,	7Fh, 80h, 81h, 81h, 81h, 82h, 82h, 82h,	83h, 84h, 84h, 83h
		db  82h, 82h, 83h, 82h,	82h, 82h, 81h, 80h, 7Fh, 7Fh, 7Fh, 7Eh,	7Eh, 7Dh, 7Ch, 7Bh
		db  7Ah, 79h, 79h, 78h,	77h, 77h, 77h, 76h, 76h, 76h, 76h, 76h,	75h, 75h, 75h, 74h
		db  73h, 73h, 72h, 72h,	72h, 71h, 70h, 70h, 6Fh, 6Fh, 6Fh, 6Fh,	6Fh, 6Fh, 6Fh, 6Fh
		db  70h, 70h, 70h, 72h,	73h, 72h, 73h, 74h, 76h, 77h, 77h, 7Ah,	7Bh, 7Bh, 7Ch, 7Eh
		db  7Fh, 80h, 81h, 83h,	83h, 85h, 86h, 86h, 88h, 89h, 89h, 89h,	8Bh, 8Bh, 8Bh, 8Ch
		db  8Eh, 8Dh, 8Ch, 8Dh,	8Eh, 8Ch, 8Ch, 8Eh, 8Dh, 8Ch, 8Dh, 8Eh,	8Dh, 8Ch, 8Ch, 8Dh
		db  8Ch, 8Ah, 8Ah, 8Ah,	8Ah, 89h, 89h, 88h, 87h, 86h, 86h, 86h,	84h, 83h, 84h, 84h
		db  82h, 82h, 82h, 81h,	80h, 7Fh, 80h, 7Fh, 7Eh, 7Dh, 7Fh, 80h,	80h, 7Fh, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h
		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h
PCM4:		db  80h, 80h, 80h, 80h,	80h, 80h, 80h, 7Fh, 7Fh, 80h, 7Eh, 81h,	81h, 78h, 8Eh, 7Bh
					; DATA XREF: ROM:BuiltinPCMListo
		db  91h,0FFh,0FFh,0FFh,0FFh,0FFh,0E1h, 1Bh,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,0CFh, 82h, 98h,0FFh,0FFh,0FFh,0FFh,0F9h,0FFh,0FFh,0FFh,0FFh,0FFh,0F6h,0BCh
		db 0BFh,0FFh,0B8h,0C7h,0FFh, 8Eh,0A7h, 74h,   0,   0,	0,   0,	  0,   0,   0,	 0
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0, 39h,0BDh,0FFh,0FFh,0FFh
		db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0F1h,0CDh,0A0h, 67h
		db  83h, 5Eh, 1Bh, 3Bh,	2Bh,   0,   0,	 0,   0,   0,	0,   0,	  5,   6, 1Dh, 5Eh
		db  8Ch,0CCh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh, 9Bh,0CAh
		db 0ECh,0CDh,0E2h,0A3h,	7Ah, 6Eh, 50h, 72h, 53h, 0Fh, 2Bh, 13h,	  0, 0Dh, 14h,	 0
		db  15h, 30h, 27h, 0Ah,	  0, 10h, 35h, 32h, 16h,   9, 14h,   6,	  6, 37h, 64h, 79h
		db 0A0h,0EAh,0FEh,0EFh,0FFh,0FFh,0FEh,0FDh,0FFh,0F2h, 9Fh, 7Ch,	7Fh, 6Eh, 6Bh, 6Eh
		db  61h, 5Eh, 60h, 57h,	40h, 43h, 53h, 2Fh, 1Fh, 34h, 32h, 10h,	  0, 31h, 3Eh,	 0
		db  10h, 58h, 45h, 67h,	95h, 70h,0A0h,0E5h,0B8h,0ADh,0D0h,0E0h,0C8h,0AAh,0BEh,0A8h
		db  9Eh,0C9h,0AAh, 99h,0D2h,0BAh, 83h,0A1h,0B2h, 9Eh, 8Fh, 77h,	6Dh, 95h,0A3h, 52h
		db  29h, 70h, 7Bh, 4Ch,	52h, 64h, 5Bh, 5Dh, 7Fh, 81h, 55h, 52h,	75h, 62h, 4Dh, 54h
		db  50h, 75h, 7Fh, 5Fh,	7Dh, 9Dh, 9Ch,0AAh,0C5h,0D9h,0CEh,0B7h,0C9h,0D5h,0AEh,0A1h
		db 0A3h, 90h, 94h, 81h,	77h, 8Dh, 68h, 69h, 8Eh, 82h, 83h, 7Ah,	77h, 87h, 6Ah, 56h
		db  67h, 70h, 65h, 48h,	49h, 5Dh, 54h, 65h, 6Bh, 57h, 67h, 67h,	72h, 9Dh, 9Ch, 87h
		db  9Fh,0ACh, 85h, 8Ch,	97h, 8Fh,0AAh, 70h, 77h,0C5h, 75h, 89h,0BFh, 7Bh, 96h,0ADh
		db  87h, 95h, 9Bh, 67h,	6Eh, 87h, 66h, 75h, 80h, 79h, 6Eh, 5Fh,	85h, 85h, 70h, 7Ah
		db  71h, 73h, 7Fh, 77h,	68h, 76h, 7Eh, 71h, 79h, 7Fh, 7Ah, 75h,	7Eh, 8Fh, 93h, 85h
		db  8Ch,0ACh,0A5h,0A2h,	9Eh, 7Dh, 6Fh, 67h, 5Ch, 5Bh, 53h, 49h,	54h, 6Dh, 72h, 61h
		db  69h, 95h,0A8h, 9Eh,0A2h,0BDh,0B3h, 9Ch,0C1h,0C5h,0A9h,0B0h,	97h, 81h, 9Ch, 90h
		db  62h, 5Fh, 64h, 51h,	45h, 53h, 64h, 48h, 48h, 85h, 74h, 56h,	84h, 7Fh, 72h, 7Eh
		db  6Ah, 6Ch, 6Fh, 64h,	6Bh, 6Eh, 64h, 4Fh, 5Eh, 81h, 75h, 5Dh,	6Eh,0A5h,0C0h,0A9h
		db 0ACh,0CDh,0C9h,0C4h,0CFh,0C3h,0C0h,0B7h,0BBh,0BCh, 8Dh, 86h,	8Bh, 68h, 60h, 6Eh
		db  5Ch, 4Ah, 59h, 51h,	3Ch, 44h, 48h, 40h, 3Fh, 4Bh, 49h, 42h,	44h, 50h, 76h, 93h
		db 0A3h,0AAh,0A7h,0B2h,0AEh, 9Ah,0A4h,0AEh,0B0h,0BEh,0BEh,0B7h,0AEh,0A1h,0A9h,0A0h
		db  91h,0A5h,0A0h, 78h,	71h, 76h, 5Fh, 52h, 51h, 4Eh, 4Fh, 4Bh,	50h, 54h, 48h, 58h
		db  70h, 6Bh, 79h, 85h,	76h, 82h, 8Dh, 7Bh, 80h, 9Fh,0A8h, 9Ah,	9Bh,0A7h, 9Fh, 8Fh
		db  93h, 9Dh, 91h, 8Ah,	8Bh, 79h, 72h, 7Ah, 74h, 72h, 7Ah, 7Bh,	78h, 7Ah, 7Fh, 71h
		db  69h, 7Ah, 83h, 78h,	76h, 80h, 7Fh, 77h, 7Ah, 7Fh, 81h, 80h,	80h, 87h, 85h, 7Eh
		db  82h, 81h, 7Dh, 83h,	7Fh, 77h, 7Fh, 83h, 7Ch, 7Dh, 7Ch, 73h,	74h, 7Bh, 7Eh, 7Eh
		db  7Dh, 7Fh, 83h, 84h,	85h, 86h, 86h, 8Ah, 8Fh, 8Bh, 85h, 83h,	84h, 85h, 7Fh, 79h
		db  7Ch, 7Ch, 7Bh, 7Ah,	75h, 79h, 7Dh, 79h, 7Bh, 80h, 7Fh, 80h,	80h, 7Eh, 7Fh, 81h
		db  81h, 81h, 82h, 82h,	81h, 7Fh, 80h, 81h, 7Fh, 80h, 81h, 7Fh,	80h, 81h, 80h, 80h
		db  80h, 81h, 82h, 80h,	80h, 81h, 80h, 7Fh, 80h, 7Fh, 7Fh, 7Fh,	7Fh, 7Fh, 7Fh, 7Fh
		db  7Fh, 7Fh, 80h, 7Fh
		ds 98Fh
sample1:	sample_entry <?>	; DATA XREF: EntryPoint+3o
					; EntryPoint+6o ...
sample0:	sample_entry <?>	; DATA XREF: EntryPoint+38o
					; EntryPoint+56r ...
driver_input:	ds 1			; DATA XREF: EntryPoint:PCMwaitloopr
					; EntryPoint+35w ...
fm_in_progress_flag:ds 1		; DATA XREF: EntryPoint+1Cw
					; EntryPoint+31w ...
		ds 1
; end of 'ROM'

; ===========================================================================

; Segment type:	Regular
		segment	YM2612
		org 4000h
zYM2612_A0:	ds 1			; DATA XREF: EntryPoint:busywaitr
					; EntryPoint+28w ...
zYM2612_D0:	ds 1			; DATA XREF: EntryPoint+2Dw
					; EntryPoint+1EBw
zYM2612_A1:	ds 1
zYM2612_D1:	ds 1
; end of 'YM2612'

; ===========================================================================

; Segment type:	Regular
		segment	BankRegister
		org 6000h
zBankRegister:	ds 1			; DATA XREF: EntryPoint+4Do
; end of 'BankRegister'

; ===========================================================================

; Segment type:	Regular
		segment	SN76489
		org 7F11h
zPSG:		ds 1
; end of 'SN76489'

; ===========================================================================

; Segment type:	Regular
		segment	ROMWindow
		org 8000h
zROMWindow:	ds 8000h		; DATA XREF: DoNextSampleBank+3o
					; DoNextSampleBank+21o
; end of 'ROMWindow'


		end
